<main role="main">
   <section id="terms_page" class="py-5">
      <div class="">
         <div class="container">
            <div class="row">
                <h1>Terms and Conditions</h1>
                
                <h3>1. Last Updated January 1, 2021 </h3>
                <p>This website and any related websites, including all Content and services, is provided as an added service to our users. Your use of this site is subject to the following terms and conditions (“Terms”).</p>
                <p>These Terms constitute a legally binding agreement made between You, whether personally or on behalf of an entity (“You”) and TaxResalePermit.com (“We,” “Us” or “Our”), concerning Your access to and use of the TaxResalePermit.com website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the “Site”).</p>
                <p> You agree that by accessing the Site, You have read, understood, and agreed to be bound by all of these Terms.</p>
                <p>IF YOU DO NOT AGREE WITH ALL OF THESE TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
                <p>By completing an application on this website, You consent to TaxResalePermit.com submitting the application on Your behalf to the state selected by You, pursuant to these Terms and with the information that You provide directly to Us.</p>
                <p>Depending on the state You select, the Permit or Certificate obtained on Your behalf may be mailed to You directly or delivered to TaxResalePermit.com electronically.  TaxResalePermit will promptly forward directly to You any Permits or Certificates received on Your behalf.</p>
                
                <h3>2. OUR SERVICES </h3>
                <p>We provide a paid Standard Service and an Expediting Service to help obtain Seller’s Permit Numbers from state offices. (“Services”). We provide assistance and a secure online order form to help and assist in providing Your information to the proper government office and to help obtain Your Seller’s Permit number. We will not be held responsible or accountable for information provided by You if deemed to be fraudulent or inaccurate. We are not affiliated with the IRS or any other governmental or regulatory body or agency and by agreeing to these terms, You understand the information provided by TaxResalePermit is not by a legal or accounting firm and does provide any legal or financial advice.</p>
                
                <h3>3. RIGHTS GRANTED</h3>
                <p>For purposes of this Agreement and to access and use the account information as part of the Services ordered, You grant TaxResalePermit a limited power of attorney, and appoint TaxResalePermit as Your attorney-in-fact and/or agent, to access third party sites, retrieve and use Your information with the full power and authority to do and perform each thing necessary in connection with such activities as to allow TaxResalePermit to process Your application as part of the services ordered.</p>
                <p>By agreeing to these Terms You are hereby providing authorization to fill out, file, and sign documents, forms, and any other items on Your behalf or on behalf of the requesting party to complete the TaxResalePermit application and receive Your Tax Resale Permit or Certificate. As such, You consent to allow TaxResalePermit intermediate service provider, transmitter or electronic return originator to send the applicable tax return forms to the proper state agency and to receive associated information from the proper state agency.</p>
                
                <h3>4. FEES AND REFUND POLICY </h3>
                <p>Depending on Your state, You may apply for a Seller’s Permit number directly with Your state at a reduced cost or potentially for free.  We provide the services for the rates listed on this website, which are clearly stated prior to ordering.</p>
                <p><b>Your purchase will show on Your bank statement with the credit card descriptor as TaxResalePermit. </b></p>            
                <p>We process all applications and transmit them to the correct Government offices as quickly as they are submitted.  Please contact Us as quickly as possible if You decide You need a refund and our customer support team will work directly with You to discuss Your individual refund request.</p>
                <p>All refunds will be determined on a case-by-case basis. We will do everything We can to process Your application in one business day, provided all information provided to Us is accurate. If We cannot complete the process and no Seller’s Permit or Certificate number is assigned due to an unfixable error, We will provide a full refund.</p>
                <p>If We do complete the application and a Seller’s Permit or Certificate is successfully assigned (service is provided), no refunds can be issued.</p>
                <p>For incomplete orders due to inaccurate information, You will be contacted via email by Us to rectify the issue, and We will try one additional time to obtain Your Seller’s Permit or Certificate number. If at that point there is another error, You will be refunded within 48 hours. </p>
                <p>If, after a good faith attempt to notify You has been made, We are unable to complete Your order and obtain Your Permit or Certificate due to Your failure or refusal to provide needed information or otherwise complete Our process, We shall not be obligated to issue You a refund.</p>
                
                <h3>5. LEGAL AND ACCOUNTING DISCLAIMER </h3>
                <p>We do not verify, and are not responsible for, the accuracy of the information submitted by You to Us.  We are not a legal or accounting firm, We do not offer legal or tax advice or recommendations, and nothing We say or do should be construed as such.  Our communications are not protected by attorney-client or accountant-client privilege in any way.  Any individual who needs legal or tax assistance should contact an attorney or accountant licensed in their jurisdiction.</p>
                
                <h3>6. RELEASE OF LIABILITY </h3>
                <p>WE, INCLUDING ANY OF OUR AFFILIATES, SUCCESSORS, ASSIGNS, AND RESPECTIVE OFFICERS, DIRECTORS, AGENTS, REPRESENTATIVES, EMPLOYEES, CONTRACTORS, LICENSORS, AND LICENSEES, (“RELEASED PARTIES”) ARE NOT LIABLE TO YOU FOR ANY AND ALL SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL INJURIES OR DAMAGES, ARISING FROM OR RELATED TO THESE TERMS AND ACCESS AND USE OF WEBSITE AND SERVICES, INCLUDING BODILY INJURY, DEATH, LOSS OF REVENUE, LOSS OR CORRUPTION OF DATA, PROFITS, OR OPPORTUNITIES, AND CLAIMS BY ANY THIRD PARTY, EVEN IF YOU OR ANY THIRD PARTY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. WE ARE NOT LIABLE FOR ANY FAILURE OR DELAY DUE TO MATTERS BEYOND OUR REASONABLE CONTROL, INCLUDING FORCE MAJEURE. THIS APPLIES TO ALL CAUSES OF ACTION IN THE AGGREGATE, INCLUDING BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, AND OTHER TORTS. </p>
                <p>BY ACCESSING AND USING THIS WEBSITE AND SERVICES, YOU AGREE NOT TO SUE OR INSTITUTE ANY CAUSE OF ACTION OR ANY LEGAL PROCEEDING AGAINST THE RELEASED PARTIES. IN NO EVENT SHALL ANY LIABILITY OF THE RELEASED PARTIES RELATED TO THESE TERMS AND ACCESS AND USE OF WEBSITE OR SERVICES EXCEED THE FEES PAID BY YOU TO US DURING THE 12 MONTHS IMMEDIATELY PRECEDING THE CLAIM OR EVENT GIVING RISE TO SUCH LIABILITY. </p>
                
                <h3>7. CALIFORNIA RESIDENTS</h3>
                <p>IF YOU ARE A CALIFORNIA USER, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.” THE FOREGOING SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW. </p>
                
                <h3>8. INDEMNIFICATION</h3>
                <p>You agree to release, indemnify, defend, protect, compensate, reimburse, and hold harmless each of the Released Parties from and against any and all claims, damages, losses, costs, fees (including reasonable attorneys’ fees), liabilities, or injuries suffered arising out of, or relating to, these Terms and the access and use of this Site to the fullest extent provided by applicable law. This includes Your breach of any warranty, representation, covenant, or other term of provision of these Terms, violation of applicable laws or regulations, negligent acts or omissions, and any content posted, submitted, or otherwise made available on Website or in connection with Services. </p>
                <p>We will promptly notify You of any claim for indemnification. All provisions of these Terms regarding indemnification shall survive termination of our relationship and these Terms. The foregoing shall not apply to the extent prohibited by applicable law.</p>
                
                <h3>9. LIMITATIONS OF LIABILITY </h3>
                <p>THIS SITE IS MADE AVAILABLE TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS, UNLESS OTHERWISE SPECIFIED IN WRITING. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, TAXRESALEPERMIT DISCLAIMS ALL WARRANTIES EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE. TAXRESALEPERMIT SPECIFICALLY DISCLAIMS ANY REPRESENTATIONS OR WARRANTIES THAT ANY GOVERNMENTAL INFORMATION (INCLUDING INFORMATION REGARDING TAX RATES OR THE APPLICABILITY OF CERTAIN TAXES) ARE ACCURATE, CURRENT, OR APPLICABLE TO YOU OR YOUR BUSINESS. TAXRESALEPERMIT’S TOTAL LIABILITY ARISING OUT OF THE SITES, WHETHER ON BREACH OF CONTRACT, BREACH OF WARRANTY, CLAIM OF NEGLIGENCE, OR OTHERWISE, SHALL NOT IN ANY CASE EXCEED THE COST PAID BY YOU TO ACCESS THIS SITE OR $50, WHICHEVER IS LESS, AND TAXRESALEPERMIT SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INCIDENTAL, CONSEQUENTIAL, OR SPECIAL DAMAGES.</p>
                
                <h3>10. GOVERNING LAW</h3>
                <p>These Terms and Your use of the Site and the Marketplace Offerings are governed by and construed in accordance with the laws of the State of Texas applicable to agreements made and to be entirely performed within the State of Texas, without regard to its conflict of law principles.  The parties hereby consent to the exclusive jurisdiction and venue in the state courts in Denton County, Texas, or their respective federal courts. THE PARTIES AGREE THAT ANY DISUPTE ARISING OUT OF THIS AGREEMENT OR THE SERVICES SHALL BE HEARD BY A JUDGE, AND NOT A JURY.</p>
                
            </div>
         </div>
      </div>
   </section>
</main>